title: GeekNews
email: your-email@example.com
description: >-
  개발/기술/스타트업 뉴스 서비스
baseurl: ""
url: "https://Sungheyn.github.io"

author:
  name: GeekNews
  email: your-email@example.com

# theme: minima  # Using custom layout instead

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

header_pages:
  - about.md
  - archive.md

show_excerpts: true
